### ISSUE TITLE
Docker image build error..

### ISSUE THREAD

**Issue by zhuhu00** [tatsuyai713/ROS-2-on-ARM64-Mac-via-Docker#1]
I am using the latest 14-inch version of macbook pro, and the chip is M1 pro, but there are some problems when I build this dockerfile and I don't know how to solve them. Can you provide some ideas?
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/29742046/169336398-5918645d-ad78-4872-802a-547592d1f754.png">

**Comment by UaRYd** [comment]
Are you living in China? If yes, you should build it via VPN(except Hongkong node). Because *.githubusercontent.com has already been banned by GFW in China and HK.
