### ISSUE TITLE
Cannot access to GUI..

### ISSUE THREAD

**Issue by zang09** [tatsuyai713/ROS-2-on-ARM64-Mac-via-Docker#2]
I cannot access to gui, while using parallels client. 
I try to connect on localhost:3389 but it fails..
Is there any idea??

**Comment by Wissiak** [comment]
Same here. Output looks good:
![Screenshot 2023-03-10 at 15 45 38](https://user-images.githubusercontent.com/31206249/224345765-5c48d9cf-36e4-4764-9f16-2649f881dab3.png)

But connection fails from Parallels Client:
![image](https://user-images.githubusercontent.com/31206249/224345923-71cb2ae8-fbce-4993-af8e-6bcdea969dbc.png)

![image](https://user-images.githubusercontent.com/31206249/224345968-82b08533-b515-4de2-91a6-6f037277f0ca.png)

Connection does neither work with port 3350 (as from the output log).

**Comment by darebear** [comment]
@zang09 , @Wissiak , after a bit of debugging the method on the following link worked for me (and there are other success cases): https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285

```
d@dMBP ROS_on_M1_Mac_Docker % export HOSTNAME=`hostname`
d@dMBP ROS_on_M1_Mac_Docker % export DISPLAY=${HOSTNAME}:0
d@dMBP ROS_on_M1_Mac_Docker % echo $DISPLAY
dMBP:0
d@dMBP ROS_on_M1_Mac_Docker % docker run -it \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    osrf/ros:noetic-desktop-full \
    rqt
    
Output: 
export containerId=$(docker ps -l -q)
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

That said, I cannot get Gazebo to run. I'm going to switch to an ARM64 image, the one in this repo, and then do further debugging but maybe this helps you two along.
