### ISSUE TITLE
Cannot obtain image

### ISSUE THREAD

**Issue by ckive** [tatsuyai713/ROS-2-on-ARM64-Mac-via-Docker#3]
<br>
FROM ghcr.io/tatsuyai713/development-container-for-ros-2-on-m1-2-mac:v0.01
   2 |     
   3 |     ARG UID=9001
--------------------
ERROR: failed to solve: ghcr.io/tatsuyai713/development-container-for-ros-2-on-m1-2-mac:v0.01: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Atatsuyai713%2Fdevelopment-container-for-ros-2-on-m1-2-mac%3Apull&service=ghcr.io: 401 Unauthorized

**Comment by rgsk** [comment]
I am facing the same issue

**Comment by tatsuyai713** [comment]
I'm sorry. Now, I change the container registry visibility setting.

**Comment by ckive** [comment]
All good!
